gantt
    title Planificación Round Robin (Q=3) - Parte 2 (15-21s)
    dateFormat X
    axisFormat %s
    
    section CPU
    P1(15-18)    :active, cpu8, 15, 18
    P2(18-20)    :active, cpu9, 18, 20  
    P4(20-21)    :active, cpu10, 20, 21

    section Estado
    P3_Terminado :done, term1, 14, 14
    P1_Terminado :done, term2, 18, 18
    P2_Terminado :done, term3, 20, 20
    P4_Terminado :done, term4, 21, 21