name: Build Book

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Para publicar PDF en un release cuando tagueás una versión
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache TeX Live
      uses: actions/cache@v3
      with:
        path: /usr/share/texlive
        key: texlive-${{ runner.os }}-2025

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-spanish

    - name: Install Mermaid CLI
      run: npm install -g @mermaid-js/mermaid-cli@latest

    - name: Compile PDF with Makefile
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: build/Introduccion_a_los_Sistemas_Operativos.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: book
        path: build
    - name: Upload PDF to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/Introduccion_a_los_Sistemas_Operativos.pdf